(
    select
        replace(RPY_PACT_ID, chr(0), '') as RPY_PACT_ID,
        RPY_CLS_SEQ,
        APY_STR_DT,
        RPY_SEQ,
        CORG_SEQ,
        replace(HSP_TP_CD, chr(0), '') as HSP_TP_CD,
        replace(PT_NO, chr(0), '') as PT_NO,
        replace(CORG_CD, chr(0), '') as CORG_CD,
        replace(CORG_TP_CD, chr(0), '') as CORG_TP_CD,
        replace(RDTN_RSN_CD, chr(0), '') as RDTN_RSN_CD,
        replace(UNCL_RSN_CD, chr(0), '') as UNCL_RSN_CD,
        INS_RTO,
        NINS_RTO,
        CMED_RTO,
        CTFS_RTO,
        EXCP_RTO,
        INS_AMT,
        NINS_AMT,
        CMED_AMT,
        CTFS_AMT,
        EXCP_AMT,
        SUM_AMT,
        replace(BOBD_PT_NO, chr(0), '') as BOBD_PT_NO,
        BIND_DTM,
        replace(BIND_STF_NO, chr(0), '') as BIND_STF_NO,
        RPY_STS_CD,
        CNCL_DT,
        TOJ_CMED_AMT,
        TOJ_CORG_CMED_RTO,
        FSR_DTM,
        replace(FSR_STF_NO, chr(0), '') as FSR_STF_NO,
        replace(FSR_PRGM_NM, chr(0), '') as FSR_PRGM_NM,
        null FSR_IP_ADDR,
        LSH_DTM,
        replace(LSH_STF_NO, chr(0), '') as LSH_STF_NO,
        replace(LSH_PRGM_NM, chr(0), '') as LSH_PRGM_NM,
        null LSH_IP_ADDR,
        PTHS_CRRT_AMT,
        PTHS_CRRT_RTO,
        GNR_AMT,
        GNR_RTO,
        AMT_APY_YN,
        MTRL_AMT,
        MTRL_RTO,
        NMC_MTRL_AMT,
        sysdate CDW_LOD_DTM
    from
        DKUH_HIS.ACPPRIOE) sub
